apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-resource-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx-resources

  template:
    metadata:
      labels:
        app: nginx-resources

    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "128Mi"