apiVersion: v1
kind: PersistentVolume

metadata:
  name: day14-pv

spec:
  capacity:
    storage: 1Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /mnt/day14-data
    type: DirectoryOrCreate